apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: consul
  name: consul
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    app.kubernetes.io/component: consul
