apiVersion: v1
kind: Service
metadata:
  name: my-cortex-distributor-headless
  labels:
    app.kubernetes.io/component: distributor
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9095
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/component: distributor
