apiVersion: v1
kind: Service
metadata:
  name: ingester
  labels:
    app.kubernetes.io/component: ingester
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/component: ingester
