apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # dependences
  - consul.yaml
  - consul-svc.yaml
  - minio.yaml
  - minio-svc.yaml
  - prometheus.yaml
  # cortex
  - ingester.yaml
  - ingester-headless-svc.yaml
  - ingester-svc.yaml
  - distributor.yaml
  - distributor-headless-svc.yaml
  - distributor-svc.yaml
  - querier.yaml
  - querier-svc.yaml
  - querier-headless-svc.yaml
  - store-gateway.yaml
  - compactor.yaml

configMapGenerator:
  - name: cortex
    files:
      - cortex.yaml
  - name: prometheus
    files:
      - prometheus.yml

