apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - consul.yaml
  - consul-svc.yaml
  - minio.yaml
  - minio-svc.yaml
  - ingester.yaml
  - ingester-headless-svc.yaml
  - ingester-svc.yaml
  - distributor.yaml
  - distributor-headless-svc.yaml
  - distributor-svc.yaml

configMapGenerator:
  - name: cortex
    files:
      - cortex.yaml
