apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  labels:
    app.kubernetes.io/component: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/component: memcached
    spec:
      containers:
        - name: memcached
          image: "memcached:1.6.10"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 11211
              protocol: TCP
