apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio
    spec:
      containers:
      - image: minio/minio:RELEASE.2020-10-28T08-16-50Z-48-ge773e06e5
        name: minio
        lifecycle:
          postStart:
            exec:
              command: ["mkdir", "-p", "/data/tsdb"]
        ports:
        - containerPort: 9001
        - containerPort: 9000
        env:
          - name: MINIO_ACCESS_KEY
            value: miniokey
          - name: MINIO_SECRET_KEY
            value: miniokey
        args:
          - server
          - /data
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
